// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kylrkuwujlvankuwqqdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5bHJrdXd1amx2YW5rdXdxcWRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NzE2OTYsImV4cCI6MjA3NDM0NzY5Nn0.lN63THeTMWFGhVm4wrba7lQX1jjAeU20C2vs2jy_gEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});